[features]
seeds = false
skip-lint = false

[programs.localnet]
trustlayer_vault = "Fg6PaFpoGXkYsidMpWxTWqifpVxgkZ5T8U5Lnd4L3bG"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "node backend/test/reward-engine.test.js"
